-- Nexa Phase 2: seed realistic jobs
-- Modern, believable companies and roles. Fully remote, open to Africa.

insert into public.jobs (slug, title, company, company_logo, description_md, apply_url, category, location, country, salary_range, employment_type, tags, is_remote, is_open_to_africa, source, source_id, expires_at)
values
  (
    'senior-frontend-engineer-linear-remote-global',
    'Senior Frontend Engineer',
    'Linear',
    null,
    E'## About the role\n\nLinear is hiring a Senior Frontend Engineer to work on the core product used by thousands of software teams. You will own meaningful surface area across the editor, issue views, and real-time collaboration.\n\n## What you will do\n\n- Build and maintain core product surfaces in TypeScript and React.\n- Collaborate with design on interaction details and motion.\n- Improve performance, reliability, and accessibility.\n\n## What we look for\n\n- Strong TypeScript and React experience.\n- Care for product quality and details.\n- Experience with real-time or collaborative software is a plus.',
    'https://linear.app/careers',
    'engineering',
    'Remote',
    'Global',
    '$140k - $190k',
    'full_time',
    array['typescript','react','frontend','remote'],
    true, true, 'seed', 'seed-1', now() + interval '45 days'
  ),
  (
    'product-designer-vercel-remote-global',
    'Product Designer',
    'Vercel',
    null,
    E'## About the role\n\nVercel is hiring a Product Designer to shape the experience of building and shipping on the web.\n\n## Responsibilities\n\n- Design end-to-end product flows for the Vercel dashboard.\n- Partner with engineering to ship polished interfaces.\n- Contribute to the design system.\n\n## Requirements\n\n- 4+ years designing modern SaaS products.\n- Strong systems thinking and visual craft.\n- Comfort with developer-facing products.',
    'https://vercel.com/careers',
    'design',
    'Remote',
    'Global',
    '$130k - $170k',
    'full_time',
    array['product-design','figma','design-systems'],
    true, true, 'seed', 'seed-2', now() + interval '45 days'
  ),
  (
    'backend-engineer-supabase-remote-emea',
    'Backend Engineer',
    'Supabase',
    null,
    E'## About the role\n\nSupabase is looking for a Backend Engineer to work across Postgres tooling, auth, and storage.\n\n## What you will do\n\n- Build and maintain core backend services.\n- Improve performance and reliability of database tooling.\n- Contribute to open source.\n\n## Requirements\n\n- Strong experience with Postgres.\n- Comfort with Go, Rust, or TypeScript.\n- Open source experience preferred.',
    'https://supabase.com/careers',
    'engineering',
    'Remote',
    'EMEA',
    '$120k - $170k',
    'full_time',
    array['postgres','backend','open-source'],
    true, true, 'seed', 'seed-3', now() + interval '45 days'
  ),
  (
    'developer-advocate-resend-remote-global',
    'Developer Advocate',
    'Resend',
    null,
    E'## About the role\n\nResend is hiring a Developer Advocate to help developers ship better email experiences.\n\n## What you will do\n\n- Write technical content and tutorials.\n- Contribute to SDKs and examples.\n- Speak at events and run workshops.\n\n## Requirements\n\n- Strong writing and communication skills.\n- Production experience with modern web stacks.\n- Comfort with public speaking.',
    'https://resend.com/careers',
    'marketing',
    'Remote',
    'Global',
    '$110k - $150k',
    'full_time',
    array['devrel','content','community'],
    true, true, 'seed', 'seed-4', now() + interval '45 days'
  ),
  (
    'data-engineer-posthog-remote-global',
    'Data Engineer',
    'PostHog',
    null,
    E'## About the role\n\nPostHog is hiring a Data Engineer to work on large-scale analytics infrastructure.\n\n## What you will do\n\n- Maintain ClickHouse-backed data pipelines.\n- Improve ingestion and query performance.\n- Partner with product engineers on new features.\n\n## Requirements\n\n- Experience with columnar databases (ClickHouse, BigQuery, or similar).\n- Strong Python or TypeScript.\n- Interest in product analytics.',
    'https://posthog.com/careers',
    'data',
    'Remote',
    'Global',
    '$130k - $180k',
    'full_time',
    array['clickhouse','python','analytics'],
    true, true, 'seed', 'seed-5', now() + interval '45 days'
  ),
  (
    'product-manager-paystack-remote-africa',
    'Product Manager',
    'Paystack',
    null,
    E'## About the role\n\nPaystack is hiring a Product Manager to lead initiatives across our merchant products.\n\n## What you will do\n\n- Own product strategy for a core merchant surface.\n- Partner with design and engineering.\n- Work directly with merchants across Africa.\n\n## Requirements\n\n- 3+ years of product management experience.\n- Experience with payments or fintech preferred.\n- Strong written communication.',
    'https://paystack.com/careers',
    'product',
    'Remote',
    'Nigeria',
    '$80k - $120k',
    'full_time',
    array['fintech','payments','africa'],
    true, true, 'seed', 'seed-6', now() + interval '45 days'
  ),
  (
    'customer-support-engineer-railway-remote-global',
    'Customer Support Engineer',
    'Railway',
    null,
    E'## About the role\n\nRailway is hiring a Customer Support Engineer to help developers ship and operate apps in production.\n\n## What you will do\n\n- Help users debug deployments, builds, and runtime issues.\n- Triage and escalate issues to engineering.\n- Improve documentation.\n\n## Requirements\n\n- Strong technical background.\n- Comfort with Linux, Docker, and modern web stacks.\n- Excellent written communication.',
    'https://railway.app/careers',
    'customer-support',
    'Remote',
    'Global',
    '$70k - $110k',
    'full_time',
    array['support','docker','linux'],
    true, true, 'seed', 'seed-7', now() + interval '45 days'
  ),
  (
    'senior-product-designer-flutterwave-remote-africa',
    'Senior Product Designer',
    'Flutterwave',
    null,
    E'## About the role\n\nFlutterwave is hiring a Senior Product Designer to lead design on core payment products.\n\n## What you will do\n\n- Lead design on a major product area.\n- Partner with research and engineering.\n- Mentor other designers.\n\n## Requirements\n\n- 5+ years of product design experience.\n- Strong portfolio of shipped work.\n- Comfort working across Africa-wide markets.',
    'https://flutterwave.com/careers',
    'design',
    'Remote',
    'Africa',
    '$90k - $130k',
    'full_time',
    array['product-design','fintech','africa'],
    true, true, 'seed', 'seed-8', now() + interval '45 days'
  ),
  (
    'platform-engineer-fly-io-remote-global',
    'Platform Engineer',
    'Fly.io',
    null,
    E'## About the role\n\nFly.io runs apps close to users. We are hiring a Platform Engineer to work on our orchestrator and edge runtime.\n\n## What you will do\n\n- Work on core platform services in Elixir and Go.\n- Improve reliability and observability.\n- Contribute to public technical writing.\n\n## Requirements\n\n- Strong systems background.\n- Experience with distributed systems.\n- Comfort owning production systems.',
    'https://fly.io/jobs',
    'engineering',
    'Remote',
    'Global',
    '$150k - $200k',
    'full_time',
    array['elixir','go','distributed-systems'],
    true, true, 'seed', 'seed-9', now() + interval '45 days'
  ),
  (
    'growth-marketer-cursor-remote-global',
    'Growth Marketer',
    'Cursor',
    null,
    E'## About the role\n\nCursor is hiring a Growth Marketer to help developers discover and adopt the editor.\n\n## What you will do\n\n- Run experiments across acquisition surfaces.\n- Partner with content and product on lifecycle.\n- Own growth metrics end-to-end.\n\n## Requirements\n\n- Strong analytical background.\n- Experience marketing developer tools.\n- Comfort with SQL and product analytics.',
    'https://cursor.com/careers',
    'marketing',
    'Remote',
    'Global',
    '$120k - $160k',
    'full_time',
    array['growth','devtools','analytics'],
    true, true, 'seed', 'seed-10', now() + interval '45 days'
  )
on conflict (slug) do nothing;
